databases:
  - name: speakup-db
    databaseName: speakup
    user: speakup_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: speakup-web
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn speakup.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: speakup-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DJANGO_SETTINGS_MODULE
        value: "speakup.settings.production"
      - key: ALLOWED_HOSTS
        value: "speakup-web.onrender.com"


